elastic/connectors-ruby

connectors-api/src/main/ruby/connectors_errors.rb

Issue for discussion.
The error added in this PR is the error that is specific to the Enterprise Search handling of connectors - it does not get thrown by any connector.
However, `connectors_errors` file contains some errors that are framework specific, as I saw.
Question: should these errors (such as `JobClaimingError`, `JobCannotBeUpdatedError`) be moved back to Enterprise Search along with ConnectorNotAvailableError?

Add ConnectorNotAvailable Error - used by External Connector Framework

---

Gemfile
Gemfile.lock
README.md
connectors-api/pom.xml
connectors-api/src/main/ruby/connectors_logger.rb
connectors-api/src/test/ruby/connectors_logger_test.rb
connectors-stubs/NOTICE.txt
connectors-stubs/NOTICE.txt.template
connectors-stubs/pom.xml
connectors-stubs/src/main/resources/META-INF/NOTICE.txt
connectors-stubs/src/main/ruby/app_config.rb
connectors-stubs/src/test/ruby/app_config_test.rb
pom.xml
script/rspec

This adds the main connectors logger class to our connectors-api module.
It also adds a stub `AppConfig` class

Move connectors logger

---

Gemfile
Gemfile.lock
connectors-api/src/main/ruby/connectors_exception_tracking.rb
connectors-api/src/test/ruby/connectors_exception_tracking_test.rb
connectors-stubs/NOTICE.txt
connectors-stubs/pom.xml
connectors-stubs/src/main/resources/META-INF/NOTICE.txt
connectors-stubs/src/main/ruby/swiftype_exception_tracking.rb
connectors-stubs/src/test/ruby/swiftype_exception_tracking_test.rb
example-consumer/pom.xml
example-consumer/src/test/java/co/elastic/connectors/example/consumer/ExampleConsumerTest.groovy
hello-world-connector/pom.xml
hello-world-connector/src/main/ruby/hello_world.rb
hello-world-connector/src/test/java/co/elastic/connectors/hello/world/HelloWorldTest.groovy
license-mappings.xml
pom.xml

- moves Connectors::ConnectorsAPI::ExceptionTracking to ConnectorsExceptiontracking
- ensures that multiple layers of dependencies resolve correctly

move connectors exceptionhandling

---

lib/app/app.rb
lib/connectors_sdk/share_point/http_call_wrapper.rb
lib/connectors_shared/errors.rb

Introduce a new error class `ConnectorsShared::InvalidTokenError`. The error `ConnectorsShared::SecretInvalidError` was introduced by GitHub Apps and should only be used by GitHub Apps.

Add InvalidTokenError

---

Makefile

Tiny fix. Turns out `cp -n` ("no clobber") will return a `1` exit code if there was a file there that would have otherwise been clobbered 🤨

handle non-zero cp code

---

.ci/pipelines/connectors.groovy
Dockerfile
Gemfile
Gemfile.lock
Makefile
README.md
config/connectors.yml.example
lib/app/app.rb

Adds a Dockerfile that installs and deploys the app using Ubuntu Focal
Also Fixes #64

Added Docker support

---

lib/app/app.rb
lib/connectors_sdk/base/extractor.rb
lib/connectors_sdk/office365/config.rb
lib/connectors_sdk/office365/custom_client.rb
lib/connectors_sdk/office365/extractor.rb
lib/connectors_sdk/share_point/http_call_wrapper.rb
spec/connectors_sdk/office365/custom_client_spec.rb
spec/connectors_sdk/sharepoint/extractor_spec.rb

* https://github.com/elastic/ent-search/pull/6441

Return cursors at the end of extraction

---

lib/app/app.rb
lib/connectors_sdk/base/extractor.rb
lib/connectors_sdk/office365/config.rb
lib/connectors_sdk/office365/custom_client.rb
lib/connectors_sdk/office365/extractor.rb
lib/connectors_sdk/share_point/http_call_wrapper.rb
spec/connectors_sdk/office365/custom_client_spec.rb
spec/connectors_sdk/sharepoint/extractor_spec.rb

Backports the following commits to 8.2:
- Return cursors at the end of extraction (#70)

[8.2] Return cursors at the end of extraction (#70)

---

.backportrc.json
.github/PULL_REQUEST_TEMPLATE.md
docs/INTERNAL.md

Small changes noticed while working on 8.2 release things - bad docs links, missing backport config, missing gem update step.

small updates

---

lib/connectors_sdk/office365/custom_client.rb
lib/connectors_sdk/office365/extractor.rb
spec/connectors_sdk/office365/custom_client_spec.rb

[8.2][Backport] Paginate over the contents of a single SharePoint Online folder node (#69)

---

docs/RELEASING.md
lib/app/app.rb
lib/connectors_sdk/base/registry.rb
lib/connectors_sdk/share_point/http_call_wrapper.rb
spec/app_spec.rb
spec/connectors_sdk/base/registry_spec.rb
spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb

We discovered that the HttpCallWrapper instance was being shared between requests. These changes ensure it is used as a normal class/object, rather than what is effectively a singleton class. I expect this would resolve some thread-unsafe behavior.
These changes also remove the thread-unsafe behavior, but I think it's still a good idea to remove the singleton class behavior as well.
Fixed an issue where two requests to the `/documents` endpoint could interfere with each other in a thread-unsafe manner.

Stop caching the instance of HttpCallWrapper, which caused it to behave like a singleton class

---

lib/app/app.rb
lib/connectors_sdk/base/registry.rb
lib/connectors_sdk/share_point/http_call_wrapper.rb
spec/app_spec.rb
spec/connectors_sdk/base/registry_spec.rb
spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb

Backports the following commits to 8.2:
- Stop caching the instance of HttpCallWrapper, which caused it to behave like a singleton class (#83)

[8.2] Stop caching the instance of HttpCallWrapper, which caused it to behave like a singleton class (#83)

---

Makefile
make.bat

This PR adds randomness to the order of the tests that's executed by rspec. It might help us catch more potential problems with missing/incorrect `require` statements.
See discussion in https://github.com/elastic/connectors/pull/96

Randomize test order 

---

lib/connectors_sdk/office365/custom_client.rb
lib/connectors_sdk/office365/extractor.rb
lib/connectors_sdk/share_point/adapter.rb
spec/connectors_sdk/base/http_call_wrapper_spec.rb
spec/connectors_sdk/office365/custom_client_spec.rb
spec/connectors_sdk/sharepoint/adapter_spec.rb
spec/connectors_sdk/sharepoint/extractor_spec.rb

- https://github.com/elastic/ent-search/pull/6521

Add sites prefix to path

---

lib/app/app.rb
lib/connectors_sdk/base/http_call_wrapper.rb
lib/connectors_sdk/confluence_cloud/http_call_wrapper.rb
lib/connectors_sdk/share_point/http_call_wrapper.rb
spec/app_spec.rb
spec/connectors_sdk/base/http_call_wrapper_spec.rb
spec/connectors_sdk/confluence_cloud/http_call_wrapper_spec.rb
spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb

* https://github.com/elastic/ent-search/pull/6527

Add equivalent endpoint

---

.ci/pipelines/connectors.groovy
lib/connectors_shared/middleware/restrict_hostnames.rb

@tarekziade pointed out that windows tests don't really matter at the moment, and they're causing issues with surfacing CI failures (and making CI take too long) so we can disable them for now. This lets us use the "default nodes" which is `nil`, and causes us to pick up `linux && immutable`. 
This also (successfully and intentionally) exposed a bug that was present on main, causing CI to fail. So fixing that too, so that this can merge.

Disabling windows specs for now

---

spec/connectors_shared/middleware/restrict_hostnames_spec.rb

Attempt to solve problem that happens in CI pipelines:
```
[2022-05-23T13:08:42.230Z]   1) ConnectorsShared::Middleware::RestrictHostnames when external URLs are allowed by URL external domain behaves like an allowed call 
[2022-05-23T13:08:42.230Z]      Failure/Error: raise AddressNotAllowed.new("Address not allowed for #{env[:url]}") if denied?(env)
[2022-05-23T13:08:42.230Z] 
[2022-05-23T13:08:42.230Z]      ConnectorsShared::Middleware::RestrictHostnames::AddressNotAllowed:
[2022-05-23T13:08:42.230Z]        Address not allowed for https://google.com/
[2022-05-23T13:08:42.230Z]      Shared Example Group: "an allowed call" called from ./spec/connectors_shared/middleware/restrict_hostnames_spec.rb:168
[2022-05-23T13:08:42.230Z]      # …
```

Mock :getaddrinfo in restrict_hostnames_spec.rb for failing test

---

lib/connectors_async/job_runner.rb

Just cleaning up some tech debt - before I was using `puts` to output logging info, this PR changes it to use `ConnectorsShared::Logger` instead.
Ideally, the method `log_with_thread_id` should go away and we should log thread ids when running jobs natively for all code running within threads, but that's work for later.

Add proper logging into JobRunner

---

config/connectors.yml.example

This just updates and corrects the `repository` value present in the example config file.

Update/correct example `repository` value

---

README.md

There isn't much to explain here 🙂.

Minor copyedit to `readme`: add missing word to heading

---

.github/PULL_REQUEST_TEMPLATE.md
Gemfile
Gemfile.lock
config/connectors.yml.example
lib/connectors_app/config.rb
lib/connectors_shared/elasticsearch_client.rb

Add a Elasticsearch client (using [elasticsearch-ruby](https://github.com/elastic/elasticsearch-ruby))

Add Elasticsearch client

---

lib/app/connector.rb
spec/app/connector_spec.rb

I think for 8.4 it would make sense to not have any multithreading in the connector (unless we'll have a robust abstraction on top of it).
Problems that can happen now:
- If connector runs for more than 60 seconds and somebody forces a sync, second sync will start
- If connector runs too often (schedule allows for it), then it will run multiple syncs at the same time
I think currently it brings problems, thus maybe let's get rid of it until we have time to dedicate to creating a robust threading abstraction?

Drop threading from the connector (for now)

---

lib/connectors/base/connector.rb

Just a housekeeping commit - Base::Connector has a lot of stuff inside that is not used any more, cleaning up.

Clean up unused Base::Connector methods

---

lib/core/elastic_connector_actions.rb

Rename `sync_status` and `sync_error` to `last_sync_status` and `last_sync_error` in `.elastic-connectors`. See discussion [here](https://elastic.slack.com/archives/C03GAPTQ2JF/p1657121990619269)

Rename fields in .elastic-connectors

---

lib/app/console_app.rb
lib/app/worker.rb
lib/connectors/base/connector.rb
lib/connectors/gitlab/connector.rb
lib/connectors/stub_connector/connector.rb
lib/core/elastic_connector_actions.rb

System indices (currently `.elastic-connectors` and `.elastic-connectors-sync-jobs`) are created at Kibana startup. But connector service can't assume the existence of Kibana, and needs to create those indices if they are absent.

Create system indices if absent

---

lib/core/connector_settings.rb
lib/core/sync_job_runner.rb

Now when connector starts up and no configuration is there, connector just runs as is.
What happens now instead is - connector starts up and writes its default configuration into Elasticsearch if none is provided.
This way Kibana can show configurable fields to the user, so that they can do the initial connector setup.

Add connector configuration initialization

---

lib/connectors/gitlab/connector.rb

After recent PR with merge/rebase conflicts, I've introduced a bug to Gitlab connector - it does not correctly call `super()` when calling `sync()`.
This PR fixes this incorrect merge conflict resolution.

Fix gitlab connector

---

lib/connectors/base/connector.rb

Fix another merge conflict - Base::Connector does not actually require `core/output_sink` + fix wrong way to instantiate `CombinedSink`.

Fix another place for Core::OutputSink

---

lib/utility/elasticsearch/index/mappings.rb
spec/utility/elasticsearch/mappings_spec.rb

To make `search_index` more obvious this PR will rename it to `connectors_index`
* https://github.com/elastic/ent-search/pull/6657

Rename search_index to connectors_index

---

lib/core/elastic_connector_actions.rb

`update_connector_field` method is outside of `class << self`, thus not available to class methods of ElasticConnectorActions.
This PR fixes this problem by moving `update_connector_field` inside the `class << self` scope.

Move update_connector_field to the correct scope

---

lib/core/connector_settings.rb
lib/core/sync_job_runner.rb

When just starting up a connector, an error message is displayed:
```
/Users/artemshelkovnikov/git_tree/connectors/lib/core/sync_job_runner.rb:49:in `validate_configuration!': Connector expected configurable fields: [:api_token, :base_url], actual stored fields: ["api_token", "base_url"] (Core::IncompatibleConfigurableFieldsError)
```
It happens due to the fact that it's possible to declare configurable fields both way - as a symbol and as a string. When these values are de-serialized from the database, they are always stringified.
This commit aims to fix the validation, by stringifying the field names when validating them.

Make validate_configuration! not fail if configuration is validated in symbols

---

connectors_utility.gemspec

It makes `connectors_utility` compatible with ES cross-versioning.

Align with connectors gem versioning

---

lib/connectors/base/connector.rb
lib/connectors/gitlab/connector.rb
lib/connectors/mongodb/connector.rb
lib/connectors/stub_connector/connector.rb
lib/core/connector_settings.rb
lib/core/sync_job_runner.rb

A simplification step - connector instead of calling sink directly, can return documents (or in future events about documents), and the framework will use its own internals and settings to push the data into desired sink.
Change in a nutshell:
Before:
Connector decides how, when and where to ingest.
```ruby
def sync(settings)
GitLabClient.get_projects.each |do| project
@sink.ingest(project)
end
end
```
After:
Connector returns the documents to ingest, delegating ingestion itself to the framework
```ruby
def yield_documents(settings)
GitLabClient.get_projects.each |do| project
yield project
end
end
```
Upcoming future:
Connector returns events of sync - whether the document was created, updated or deleted, delegating further index operations to the framework.
```ruby
def …
```

Change connector interface

---

lib/core/elastic_connector_actions.rb
lib/core/sync_job_runner.rb

This PR
~1. Create index `.elastic-connector-sync-logs` (see schema [here](https://github.com/elastic/enterprise-search-team/issues/2157#issuecomment-1170869941)) at the connector service startup if it does not exist.~
2. Index a new job when claiming the job.
3. Update the job when completing the job.

Add sync job logs

---

lib/utility/elasticsearch/index/text_analysis_settings.rb
spec/utility/elasticsearch/text_analysis_settings_spec.rb

Make sure that `Utility::Elasticsearch::Index::TextAnalysisSettings.new(language_code: nil)` fallbacks to English settings

Unspecified language_code fallbacks to English

---

lib/app/console_app.rb
lib/connectors/base/connector.rb
lib/connectors/gitlab/connector.rb
lib/connectors/mongodb/connector.rb
lib/connectors/registry.rb
lib/connectors/stub_connector/connector.rb
lib/core/sync_job_runner.rb

Both methods are used as instance methods, while in reality they don't need to have access to the instance of `Connector` class - moreover they can enforce mis-usage of these methods.
Therefore, moving `display_name` and `configurable_fields` to be methods on the instance of class.

Make display_name and configurable_fields a part of class instead of instance

---

.backportrc.json
.ci/jobs/connectors.yml
config/connectors.yml.example

I think we missed a couple of places after renaming the repo.
Not all of them are required, but there might be less confusion this way.

following up on repo rename

---

lib/app/worker.rb
lib/core/elastic_connector_actions.rb

PR adds a simple task that is started when `App::Worker` starts and sends a heartbeat into `.elastic-connectors` index, updating `last_seen` field to current time.
If something makes the thread crash, it's not restarted - is there a way to handle it better?

Add a simple heartbeat task implementation

---

lib/connectors/gitlab/connector.rb

We're simplifying Gitlab connector by removing the file traversal for now - it's only picking up the root of the repository and does not sync file content.
It makes sense to approach this later when we start addressing the attachment/download functionality.

Simplify gitlab connector - remove file extraction

---

lib/connectors/gitlab/connector.rb
lib/connectors/mongodb/connector.rb

Problem: we create an instance of `Connector` even before connector was configured. We also have initialisation in the connectors, for example:
```ruby
@extractor = Connectors::GitLab::Extractor.new(
:base_url => remote_configuration[:base_url][:value],
:api_token => local_configuration[:api_token]
)
```
Since `remote_configuration` comes from Kibana, when user sets the values, it might not yet be available.
Thus this commit changes such initialisation to use `dig` to not raise errors if config is not fully supplied:
```ruby 
@extractor = Connectors::GitLab::Extractor.new(
:base_url => remote_configuration.dig(:base_url, :value),
:api_token => local_configuration[:api_token]
)
```

Fix connector initialisation when connector settings are not set yet

---

lib/core/output_sink/es_sink.rb
lib/core/sync_job_runner.rb

How EsSink works now:
Every N seconds it tries to automatically flush all the queue of requests into Elasticsearch. It was done to work around the problem, that the last batch of data was never sent to Elasticsearch - `@sink.flush` was never used in the end of sync.
Now with all the refactorings, it's trivial to just call `@sink.flush` in the end of sync in `SyncJobRunner.do_sync!`.
This simplifies the sink design + avoids potential awkward interactions when the timer task to flush is triggered in the middle of actual flush (rare case, nevertheless this is added complexity that can backfire).

Simplify EsSink and flush manually

---

lib/core/elastic_connector_actions.rb
lib/core/output_sink/base_sink.rb
lib/core/output_sink/combined_sink.rb
lib/core/output_sink/console_sink.rb
lib/core/output_sink/es_sink.rb
lib/core/sync_job_runner.rb

Co-authored with @mchernyavskaya 
For now following the simplest way to also account for deletions when syncing the documents from Gitlab and Mongodb.
1. The algorithm is straightforward: before sync, collect the ids of documents that are present in the ingestion index. 
2. When doing the syncs, collect the document ids from the documents that are ingested into the index
3. Compare ids from 1. and 2. and find out which ids are in 1, but not in 2 - these will be the ids to delete.
4. Bulk delete the ids from 3.
While this way is not a perfect one to move forward, it's probably good enough for now.
When we add new connector in future, that has a different model of deleting objects (Office365-related connectors are a good example) OR implement a streamed events sync for Mongo, we will …

Make the sync account for files deleted from 3rd-party service between syncs

---

lib/app/app.rb
lib/app/console_app.rb
lib/utility/logger.rb

Currently connector app is started always with `log_level: debug` even if you specify different log level.
This PR makes app respect the `log_level` option from the configuration file!

Make the application actually respect the log level

---

lib/core/elastic_connector_actions.rb

Problem happens when collecting ids of existing documents:
```
I, [2022-07-22T08:33:12.833639 #60375]  INFO -- : Starting to sync for connector 
I, [2022-07-22T08:33:12.950587 #60375]  INFO -- : Successfully claimed job for connector XXkIJYIBUQOC5cAY4OMF
E, [2022-07-22T08:33:12.953943 #60375] ERROR -- : Traceback (most recent call last):
10: from app.rb:15:in `<main>'
9: from app.rb:21:in `<module:App>'
8: from /Users/sanderphilipse/development/elastic/connectors/lib/app/worker.rb:26:in `start!'
7: from /Users/sanderphilipse/development/elastic/connectors/lib/app/worker.rb:58:in `start_polling_jobs'
6: from /Users/sanderphilipse/development/elastic/connectors/lib/app/worker.rb:58:in `loop'
5: from /Users/sanderphilipse/development/elastic/connectors/lib/app/worker.rb:60:in `block in …
```

Fix little bug with collecting existing document ids

---

lib/core/output_sink/es_sink.rb

Problem that happened with a rebase:
EsSink class contains an `@operation_queue`, but in `def flush` code attempts to use `@queue`. It's a typo.

Fix a typo in variable name

---

lib/core/sync_job_runner.rb

Minor leftover from older code: before it was possible to access connector id by `@connector_settings['_id']` but later it was hidden under the method "@connector_settings.id".
Because of this, log messages did not contain connector ids, this PR fixes this problem.

Fix connector id in SyncJobRunner class

---

lib/connectors/gitlab/connector.rb

Problem:
We have a configuration file validation that depends on itself when creating validation rules.
For instance, if connector is `gitlab`, we want to make sure that the following section is available in the configuration file:
```yaml
gitlab:
api_token: <some_api_token>
```
We cannot do it now, because we also need to parse and validate `service_type` before actually adding this validator. It's a tough problem and we'll need to have a systematic approach for it. In future we'll probably not have any connector-specific configuration in config files any more, and all config will be available from Elasticsearch.
However for now, we want to indicate that configuration is required for `gitlab` connector to run (other connectors don't need it).
This PR is an attempt to provide a quick fix …

Add simple validation for gitlab configuration

---

lib/core/elastic_connector_actions.rb

PR addressing comments in https://github.com/elastic/connectors-ruby/pull/174#pullrequestreview-1048305962:
1. Set `pit.id` to new `pit_id` that is returned with each query. Functionally it should not change anything, it's more of a safeguard in case Elasticsearch sends back new PIT Id.
2. Move `client.close_point_in_time(:index => index_name, :body => { :id => pit_id })` to `ensure` statement to attempt to close PIT once error happens in the method. This will help us clean up PIT before they expire.

Improve PIT handling

---

lib/app/console_app.rb
lib/app/worker.rb
lib/core/elastic_connector_actions.rb
lib/core/output_sink/es_sink.rb
lib/core/sync_job_runner.rb

Various logging improvements:
1. ElasticConnectorActions do not do any `info` logs any more - only debug. Callers of ElasticConnectorActions now do logging instead in a way they need to.
2. Moved some messages from "info" to "debug"
3. Added summary logging lines in the end of sync that specify number of added/deleted docs.
4. Added a dot in the end of every log line I've found

Change logging a bit to log better and more versatile.

---

lib/stubs/app_config.rb
lib/utility/logger.rb

Does not seem to be needed any more - inlined usage of `AppConfig.connectors_logger` to the only place that used it.

Remove AppConfig.connectors_logger method and everything connected to it

---

connectors_utility.gemspec
lib/app/app.rb
lib/app/console_app.rb
lib/app/initializers/02_log_level.rb
lib/app/version.rb
lib/app/worker.rb
lib/utility/es_client.rb
spec/app/worker_spec.rb

There are mixed uses of symbol and string for the key of `App::Config`. This PR makes it consistent to use symbol.

Update App::Config key to symbol

---

lib/core/elastic_connector_actions.rb

Set the following settings for system indices `.elastic-connectors` and `.elastic-connectors-sync-jobs`
```
"auto_expand_replicas": "0-3",
"number_of_replicas": "0",
```

Update system indices settings

---

lib/core/sync_job_runner.rb

As of now when a sync job runs we define `@status[:deleted_document_count] = 0` but never update it. 
This PR fixes it, allowing to track number of documents deleted by the sync job with every run

Start tracking :deleted_document_count

---

docs/CONNECTOR_PROTOCOL.md

Follow up from https://github.com/elastic/connectors-ruby/pull/211
The BYOC uses Quartz Cron syntax

The cron is using the quartz syntax

---

config/connectors.yml.example
lib/app/console_app.rb
lib/app/worker.rb
lib/core/elastic_connector_actions.rb

Remove the analyzer settings for the content index from the connector service, which should be set by Kibana when the index is created.

Remove analyzer settings for content index

---

lib/app/worker.rb
lib/core.rb
lib/core/connector_settings.rb
lib/core/elastic_connector_actions.rb
lib/core/heartbeat.rb
lib/core/sync_job_runner.rb

Several changes:
1. Move the connector status to heartbeat
2. ~Fix a bug in method `fetch_document_ids`~
3. ~Fix a name typo in `es_sink.rb`~
4. Move the configuration update to heartbeat

Move connector status update to heartbeat

---

config/connectors.yml.example
lib/app/console_app.rb
lib/app/worker.rb
lib/core/elastic_connector_actions.rb

Backports the following commits to 8.4:
- Remove analyzer settings for content index (#216)

[8.4] Remove analyzer settings for content index (#216)

---

lib/app/worker.rb
lib/core.rb
lib/core/connector_settings.rb
lib/core/elastic_connector_actions.rb
lib/core/heartbeat.rb
lib/core/sync_job_runner.rb

Backports the following commits to 8.4:
- Move connector status update to heartbeat (#198)

[8.4] Move connector status update to heartbeat (#198)

---

lib/app/console_app.rb

Fixes a problem with switching to `fugit` - `console_app.rb` was still using old `cron_parser` package to validate the cron statements.
Also make sure that the entered cron expression is a Quartz Cron one.

Fix usage of cron parser for console_app.rb

---

lib/core/heartbeat.rb

- [Make connector CONFIGURED if all configurable fields have default values (#217)](https://github.com/elastic/connectors-ruby/pull/217)

[8.4] Make connector CONFIGURED if all configurable fields have default values (#217)

---

lib/app/console_app.rb

- [Fix usage of cron parser for console_app.rb (#218)](https://github.com/elastic/connectors-ruby/pull/218)

[8.4] Fix usage of cron parser for console_app.rb (#218)

---

Makefile
lib/utility/elasticsearch/index/mappings.rb
spec/utility/elasticsearch/mappings_spec.rb

our default mappings were not creating all the expected schema fields for crawler indices, which conflicted with [the default crawler deduplication fields](https://github.com/elastic/ent-search/blob/main/shared_togo/lib/shared_togo/config_parser/schemas/connector.rb#L4-L11)
- https://github.com/elastic/ent-search/pull/6729

add default crawler mappings

---

lib/app/worker.rb
lib/core.rb
lib/core/connector_settings.rb
lib/core/scheduler.rb
lib/core/sync_job_runner.rb

A refactoring to move away the logic about the triggering of the sync to a different place.
This PR creates a `lib/core/scheduler.rb` file that got all the logic related to scheduling moved from the `lib/core/sync_job_runner.rb` file.
This will allow for simpler testing + easier feature implementation for scheduling (specifically, for the logic to notify user about the next time the job will run).

Extract logic for scheduling to a separate class

---

lib/app/worker.rb
lib/core/heartbeat.rb
lib/utility/environment.rb
spec/app/worker_spec.rb
spec/core/heartbeat_spec.rb
spec/utility/es_client_spec.rb

This PR adds 100% test coverage for `lib/app/worker.rb` file.
- Additionally, the tests that were checking the warning handling were moved to `spec/utility/es_client_spec.rb` - they seem to belong there better.
- Moved the heartbeat timer start logic into `lib/core/heartbeat.rb` + added tests to it as well

Add test coverage for lib/app/worker.rb + modify heartbeat logic for better separation of concerns

---

.github/workflows/add-labels-main.yml
.github/workflows/backport.yml

Adding Github actions to auto-backport.
Behavior:
- any PR targeting main gets `auto-backport` and `v{VERSION}` where `VERSION` is the value in the root file
- when the PR is merged into `main` a backport issue is created

added autobackport GA

---

lib/core/sync_job_runner.rb
lib/utility/es_client.rb
spec/core/sync_job_runner_spec.rb

This PR adds tests for Core::SyncJobRunner to reach full condition/code coverage.
One small change to the logic: now when connector is unable to claim the job, it will not even attempt to run the sync any more.

Add 100% spec coverage for Core::SyncJobRunner

---

lib/connectors/gitlab/extractor.rb

Cleaning up leftover code for GitLab files/folders sync that might have been confusing.
There is just one code block that needed to be removed - less than I thought. And this block was already unused. So this change should be pretty safe.

GitLab connector does not sync the files and folders properly #2461

---

lib/connectors/gitlab/extractor.rb

Backports the following commits to 8.4:
- https://github.com/elastic/enterprise-search-team/issues/2461 - cleaning up leftover code for GitLab files and folders sync (#248)

[8.4] https://github.com/elastic/enterprise-search-team/issues/2461 - cleaning up leftover code for GitLab files and folders sync (#248)

---

lib/app/worker.rb
lib/core.rb
lib/core/connector_settings.rb
lib/core/scheduler.rb
lib/core/sync_job_runner.rb

- [Extract logic for scheduling to a separate class (#235)](https://github.com/elastic/connectors-ruby/pull/235)

[8.4] Extract logic for scheduling to a separate class (#235)

---

lib/core/elastic_connector_actions.rb
spec/core/elastic_connector_actions_spec.rb

Another PR that adds a spec for our core modules - this time for `Core::ElasticCoreActions`.

Add 100% test coverage for Core::ElasticCoreActions

---

lib/app/worker.rb
lib/core/heartbeat.rb
lib/utility/environment.rb
spec/app/worker_spec.rb
spec/core/heartbeat_spec.rb
spec/utility/es_client_spec.rb

- [Add test coverage for lib/app/worker.rb + modify heartbeat logic for better separation of concerns (#236)](https://github.com/elastic/connectors-ruby/pull/236)

[8.4] Add test coverage for lib/app/worker.rb + modify heartbeat logic for better separation of concerns (#236)

---

spec/core/scheduler_spec.rb

- [Add 100% coverage for Core::Scheduler (#240)](https://github.com/elastic/connectors-ruby/pull/240)

[8.4] Add 100% coverage for Core::Scheduler (#240)

---

docs/CONNECTOR_PROTOCOL.md

- [Fix connector protocol sequence diagram (#251)](https://github.com/elastic/connectors-ruby/pull/251)

[8.4] Fix connector protocol sequence diagram (#251)

---

lib/core/elastic_connector_actions.rb
spec/core/elastic_connector_actions_spec.rb

- [Add 100% test coverage for Core::ElasticCoreActions (#252)](https://github.com/elastic/connectors-ruby/pull/252)

[8.4] Add 100% test coverage for Core::ElasticCoreActions (#252)

---

lib/core/output_sink/base_sink.rb
lib/core/output_sink/console_sink.rb
lib/core/output_sink/es_sink.rb
spec/core/output_sink/base_sink_spec.rb
spec/core/output_sink/combined_sink_spec.rb
spec/core/output_sink/console_sink_spec.rb
spec/core/output_sink/es_sink_spec.rb
spec/spec_helper.rb
spec/support/shared_examples.rb

This PR adds tests for files under `lib/core/output_sink/` directory.
Minor changes to sinks:
- Standartize `not implemented` message for BaseSink
- Use `puts` instead of `Logger.info` in ConsoleSink - it seems like usage of logger here does not make sense, cause sink is expected to always output by design
- Move `attr_accessor :index_name` for EsSink to `private` region

Add tests for Core::Output_Sink::* + refactor sinks a bit

---

lib/core/output_sink/base_sink.rb
lib/core/output_sink/console_sink.rb
lib/core/output_sink/es_sink.rb
spec/core/output_sink/base_sink_spec.rb
spec/core/output_sink/combined_sink_spec.rb
spec/core/output_sink/console_sink_spec.rb
spec/core/output_sink/es_sink_spec.rb
spec/spec_helper.rb
spec/support/shared_examples.rb

- [Add tests for Core::Output_Sink::* + refactor sinks a bit (#254)](https://github.com/elastic/connectors-ruby/pull/254)

[8.4] Add tests for Core::Output_Sink::* + refactor sinks a bit (#254)

---

lib/connectors/mongodb/connector.rb
spec/connectors/gitlab/connector_spec.rb
spec/connectors/mongodb/connector_spec.rb
spec/support/shared_examples.rb

This PR adds test coverage for our sample MongoDB connector - the coverage is 100%, but covers only basic scenarios - no negative cases, special error handling or anything. They can be added once needed.

Add tests for mongo connector

---

spec/connectors/example/connector_spec.rb

This PR adds 100% test coverage for `Connectors::Example::Connector`.

Add example connector test coverage

---

spec/connectors/example/connector_spec.rb

- [Add example connector test coverage (#267)](https://github.com/elastic/connectors-ruby/pull/267)

[8.4] Add example connector test coverage (#267)

---

lib/connectors/gitlab/connector.rb
spec/connectors/gitlab/connector_spec.rb

- [Add test coverage for Gitlab Connector  (#266)](https://github.com/elastic/connectors-ruby/pull/266)

[8.4] Add test coverage for Gitlab Connector  (#266)

---

lib/core/heartbeat.rb
spec/core/heartbeat_spec.rb

When connector service starts up, now it will attempt to populate `service_type` for the record in Kibana `.elastic-connectors` index so that service type is now displayed in Kibana.
There is still something we can follow up on later, for example when connector tries to run a sync, it should check that it runs against expected service type.
Before the fix:
After the fix:

Store service_type for connector in Kibana `.elastic-connectors` index.

---

lib/core/heartbeat.rb
spec/core/heartbeat_spec.rb

- [Store service_type for connector in Kibana `.elastic-connectors` index. (#276)](https://github.com/elastic/connectors-ruby/pull/276)

[8.4] Store service_type for connector in Kibana `.elastic-connectors` index. (#276)

---

lib/core/elastic_connector_actions.rb
lib/core/output_sink/es_sink.rb
lib/utility/es_client.rb
spec/utility/es_client_spec.rb

To be able to use `Utility::EsClient` in ent-search we need to make it independent of `App::Config`. Ent-search doesn't have `connectors.yml` file that is being used in `App::Config`.

Make EsClient independent of App::Config

---

connectors_utility.gemspec
lib/connectors_utility.rb

This PR will add `Utility::EsClient` to connectors_utility which will be used in ent-search Crawler2 namespace. 
* https://github.com/elastic/ent-search/pull/6799
* https://github.com/elastic/connectors-ruby/pull/278

Add Utility::EsClient to connectors_utility

---

docs/CONNECTOR_PROTOCOL.md
lib/core/elastic_connector_actions.rb
spec/core/elastic_connector_actions_spec.rb

We're missing some information for the **Recent Syncs** view; namely, the affected counts. This PR adds indexed and deleted counts; together, they are what the job changes.
NOTE: it's not necessarily the same as current document count at the time. Since we assume that for 8.5, we always do the full sync, the job deletes all the old documents and creates the new. So in the end, the new documents count = indexed count, and the old documents count = deleted count, because all the old documents are deleted.

[Partial] Connectors recent syncs view #2487 - affected counts on backend

---

docs/CONNECTOR_PROTOCOL.md
lib/core/connector_settings.rb
lib/core/elastic_connector_actions.rb
lib/core/output_sink/es_sink.rb
lib/core/sync_job_runner.rb
spec/core/elastic_connector_actions_spec.rb
spec/core/native_scheduler_spec.rb
spec/core/output_sink/es_sink_spec.rb
spec/core/sync_job_runner_spec.rb

This modifies the BYOC protocol (from the ruby connector client's side) to expect ingestion flags to be present in the `.elastic-connectors` document. If the settings are not there, they are looked up in the index's meta mappings. If that fails, it falls back to hardcoded default values.
These ingest settings impact which pipeline is used at request time to index documents, and what additional fields get set on the documents as they are sent to Elasticsearch.
* default pipeline definition: https://github.com/elastic/ent-search/pull/6805
* kibana PR to make these settings available: TODO
New fields were added to the definition of the `.elastic-connectors` index to represent ingest pipeline options.
- will be handled in https://github.com/elastic/enterprise-search-team/issues/2614

add ingest fields to byoc definition

---

lib/core/elastic_connector_actions.rb

Small fix for logic that makes debugging harder.
This rescue statement transforms `StandardError` to `Utility::ClientError` that is not handled by the caller differently than StandardError, but also it loses the call stack of original error, so that newly thrown error will always point to this rescue block, not to the place where original error happened.

Remove harmful rescue/raise for native_connectors method

---

lib/app/app.rb
lib/app/config.rb
lib/utility/es_client.rb
spec/app/config_spec.rb

Elasticsearch Client will use ent-search elasticsearch config if it's on Cloud.

Use ent-search elasticsearch config if it's on cloud

---

lib/core/connector_settings.rb
lib/core/elastic_connector_actions.rb
spec/core/connector_settings_spec.rb
spec/core/native_scheduler_spec.rb

This PR just does a minor refactoring for `Core::ConnectorSettings` class.
Points addressed:
- Fixed overusage of `.with_indiffirent_access` when it's not actually needed -`ElasticConnectorActions.get_connector` already returns hash with indifferent access
- All data needed to initialise an instance of `Core::ConnectorSettings` is loaded in method caller instead of being loaded by the initializer.
- Removed `dig(*args*)` method as it's not used by anyone outside of class and replaced calls to it by explicit `@elasticsearch_response.dig` calls

Refactor Core::ConnectorSettings for more consistency

---

lib/core/elastic_connector_actions.rb
tests/ftest.rb

1. Add comments to warn not to use methods `ensure_connectors_index_exists` and `ensure_job_index_exists`
2. Use default `{}` if meta is not set in connector index.

Follow-up on PR-284

---

config/connectors.yml.example
lib/app/config.rb
lib/utility/es_client.rb

Changes made in this PR:
1. When it's on Cloud, only override elasticsearch connection configs (e.g. `cloud_id`, `hosts`, `api_key`), and preserve the rest (e.g. `trace`, `log`)
2. Add new elasticsearch config `retry_on_failure`, in case there is network split.
3. Add new elasticsearch config `request_timeout`, in case the default timeout is too low.

Add retry_on_failure and request_timeout to ES client

---

lib/app/app.rb
lib/app/console_app.rb
lib/app/dispatcher_app.rb
lib/app/preflight_check.rb
spec/app/preflight_check_spec.rb

A follow-up on https://github.com/elastic/connectors-ruby/pull/284, as suggested by @tarekziade in https://github.com/elastic/connectors-ruby/pull/296#issue-1368091963:
>the service needs to try this in a loop, not exit. Also the exit status is 0, should be -1

Add system indices retries and change exit code

---

lib/connectors/base/connector.rb
lib/connectors/example/connector.rb
lib/connectors/gitlab/connector.rb
lib/connectors/mongodb/connector.rb
lib/core/heartbeat.rb
lib/core/sync_job_runner.rb
lib/utility/errors.rb
spec/connectors/example/connector_spec.rb
spec/connectors/gitlab/connector_spec.rb
spec/connectors/mongodb/connector_spec.rb
spec/core/heartbeat_spec.rb
spec/core/sync_job_runner_spec.rb

Several very related changes bundled in one:
- Changed `Connectors::Base::Connector` method signature from `source_status` to `is_healthy?`. The method now always returns just a true or false.
- Changed base `Connectors::Base::Connector` method `health_check` to `do_health_check` - I think that this method method gives a better hint that this method is not supposed to return anything, but just "do something and raise an error"
- Added `Connectors::Base::Connector#do_health_check!` that raises `HealthCheckFailedError`if health check fails. 
- To improve on the previous point, I changed `Example::Connector.do_health_check` to include a comment that explains it and sample `raise` statement that user can uncomment and see what happens.
- Now when connector tries to run a sync, it always …

Improve and refactor health checks; add healthcheck before a sync

---

lib/core/connector_settings.rb
lib/core/native_scheduler.rb
lib/core/single_scheduler.rb

Some bug fixing and refactors:
1. changes to `connector_settings` method of `NativeScheduler` and `SingleScheduler`, to make sure they always return `[]` if something bad happens
2. Add `.with_indifferent_access` to `initialize` method of `Core::ConnectorSettings`. I remembered @artem-shelkovnikov made the change to remove it, but I think it's reasonable to keep it as we use symbolic keys in `Core::ConnectorSettings` and it does no harm to call `with_indifferent_access` twice (I actually encountered an issue because of this).
3. Move `initialize` method of `Core::ConnectorSettings` to public. I don't understand how it worked before, but we have method calls like below, and I think it's reasonable to make it public.
https://github.com/elastic/connectors-ruby/blob/2bc25637418b142cdfb2138c120 …

Connector service refactor

---

lib/connectors/base/connector.rb
lib/connectors/example/connector.rb
lib/connectors/gitlab/connector.rb
lib/connectors/mongodb/connector.rb
spec/connectors/example/connector_spec.rb
spec/connectors/mongodb/connector_spec.rb

Simplifying the code - functions  `do_health_check`, `do_health_check!` and `is_healthy?` take one argument that is never used, therefore I'm deleting this argument in this PR.

Remove params from do_health_check, do_health_check! and is_healthy?

---

lib/app/console_app.rb
lib/app/worker.rb
lib/core/connector_settings.rb
lib/core/elastic_connector_actions.rb
lib/core/heartbeat.rb
lib/core/native_scheduler.rb
lib/core/single_scheduler.rb
spec/app/worker_spec.rb
spec/core/connector_settings_spec.rb
spec/core/elastic_connector_actions_spec.rb
spec/core/heartbeat_spec.rb
spec/core/native_scheduler_spec.rb
spec/core/single_scheduler_spec.rb
tests/ftest.rb

Found a problem that `ElasticConnectorActions` and `ConnectorSettings` classes have a circular dependency. 
It happens because `Core::ElasticConnectorActions.native_connectors` attempts to create instances of `Core::ConnectorSettings` inside of the method, while `Core::ConnectorSettings.fetch_by_id` instead just calls `Core::ElasticConnectorActions.get_connector` to get the connector and does creation on its side.
Resolution is - make `Core::ElasticConnectorActions.native_connectors` more primitive "query" method that does not attempt to stitch pages/join results and move the stitching/creation logic into a method in `Core::ConnectorSettings`, see `Core::ConnectorSettings.fetch_native` method.
As a side effect added a test that checks that when fetching native connectors we ask the server …

Resolve circular dependency between ElasticConnectorActions and ConnectorSettings

---

lib/connectors/crawler/scheduler.rb
lib/core/connector_settings.rb
spec/connectors/crawler/crawler_scheduler_spec.rb

This will fix `Crawler::Scheduler` after `ElasticConnectorActions` [refactoring](https://github.com/elastic/connectors-ruby/pull/300)

Use Core::ConnectorSettings in Crawler::Scheduler

---

Gemfile
Gemfile.lock
lib/app/config.rb
lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

This PR adds handling of auth for MongoDB connector + bumps MongoDB gem to support more mongodb installations.
Now it's possible to connect using different setups:
- Cloud version of MongoDB hosted by mongodb.net
This can be done setting `host` to for example: `mongodb+srv://some_cluster.mongodb.net`
- Locally hosted version of MongoDB without discovery enabled
This can be done with several steps - first setting `host` to for example: `host: mongodb://127.0.0.1:27021'. and then setting a configuration option in `config/connectors.yml`:
```
mongo:
direct_connection: true
```
Both anonymous access and basic auth are supported!

Add auth handling to MongoDB connector

---

lib/connectors/mongodb/connector.rb

Consistency change: let's make `mongo` connector service_type `mongodb` instead (Kibana creates native connectors with this service type now, and I find it better)

Change service_type: mongo -> mongodb

---

lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

Big mistake by me when adding logic that adds basic auth for mongo in this line:
```
client = client.with(
user: @user,
password: @password
)
```
This line actually creates an new client for this MongoDB instance and overwrites content of `client` variable with it. Old client is left hanging indefinitely and never deallocates the resources, and since new client is actually not an independent client - it's "derivative" client, it seems to also not deallocate the resources any more.
This PR removes usage of `client.with` and just initialize client once and not do fancy stuff with it.

Fix MongoDB leaking threads if auth is provided

---

lib/utility/es_client.rb

Problem found: when doing bulk insert/delete operations and an error happened, we always just pick the first operation and display it in the error message, when in reality it can be any operation in the array.
This PR attempts to find the first index/delete operation that failed and use it as an error.
If no error is found, another error message is displayed.

Display actual first error that happened when applying bulk operations

---

lib/connectors/base/connector.rb

Minor typo/bug fix, there's no `Utility::Errors::` namespace, all errors are in `Utility::` namespace - whether it's good or bad.

Base::Connector uses invalid namespace for HealthCheckFailedError

---

connectors_utility.gemspec
lib/app/config.rb
lib/app/console_app.rb
lib/app/preflight_check.rb
lib/app/version.rb
lib/core/elastic_connector_actions.rb
lib/core/output_sink/es_sink.rb
lib/utility/environment.rb
lib/utility/es_client.rb
lib/utility/logger.rb
spec/utility/es_client_spec.rb

`rubyconfig` supports both dot notation and `[]` access to the config object, and we mixed the usages in the code.
This PR is to make it consistent to use dot notation.

Use dot notation for App::Config

---

README.md
lib/app/config.rb
lib/connectors/base/connector.rb
lib/connectors/example/connector.rb
lib/connectors/gitlab/connector.rb
lib/connectors/mongodb/connector.rb
lib/connectors/registry.rb
lib/utility/errors.rb
spec/connectors/example/connector_spec.rb
spec/connectors/gitlab/connector_spec.rb
spec/connectors/mongodb/connector_spec.rb

With the decision made to store credentials in clear text in 8.5, the local configuration is no longer needed.

Remove local_configuration

---

connectors_utility.gemspec
lib/app/config.rb
lib/app/console_app.rb
lib/app/preflight_check.rb
lib/app/version.rb
lib/core/elastic_connector_actions.rb
lib/core/output_sink/es_sink.rb
lib/utility/environment.rb
lib/utility/es_client.rb
lib/utility/logger.rb
spec/utility/es_client_spec.rb

This reverts commit 3fab4706b8f85c53ead7069729312b32fd9a8948.
Those changes are incompatible for ent-search 8.5

Revert "Use dot notation for App::Config (#319)"

---

lib/core/connector_settings.rb

default `run_ml_inference` to `true`
- https://github.com/elastic/connectors-python/pull/61
- https://github.com/elastic/kibana/pull/141161
- https://github.com/elastic/ent-search/pull/6852

run ml inference by default

---

lib/connectors/mongodb/connector.rb

Adding a kind of coersion to massage the string property into boolean.
* [Kibana PR](https://github.com/elastic/kibana/pull/141457)

Fix parsing on boolean values in "Direct Connect" MongoDB field

---

lib/utility/exception_tracking.rb
lib/utility/logger.rb
spec/utility/logger_spec.rb

- [Add more ECS fields (#321)](https://github.com/elastic/connectors-ruby/pull/321)

[8.5] Add more ECS fields (#321)

---

.github/PULL_REQUEST_TEMPLATE.md

Based on recent issues with introducing breaking changes to `ent-search`, I'm proposing to return the checklist item to check that gems are tested against Enterprise Search

Update Pull Request Template to include a manual gem testing step

---

connectors_utility.gemspec
lib/app/dispatcher.rb
lib/connectors/crawler/scheduler.rb
lib/core/scheduler.rb
spec/app/dispatcher_spec.rb
spec/core/scheduler_spec.rb

- [Move service type check to xxx_registered? methods (#327)](https://github.com/elastic/connectors-ruby/pull/327)

[8.5] Move service type check to xxx_registered? methods (#327)

---

lib/core/scheduler.rb

It's too noisy in the crawler logs (most probably in connectors service as well) so PR will change log level for a few calls

Change log level to reduce noise in the logs

---

lib/connectors/sync_status.rb
lib/core/elastic_connector_actions.rb
spec/core/elastic_connector_actions_spec.rb

Fixed the problem with sync displayed incorrectly in the interface if an error happened. The error happened because the job sync status enum had incorrect value representing the sync error that does not follow the protocol.

Fix last sync status FAILED to follow the protocol

---

lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

Mark a configuration with a non-existing database or collection as wrong and show a hint, which databases/collections exist. Also separate the variable for the database/collection configuration parameter and the stubbed return value within the test to be able to reflect a missing database/collection more explicitly.

Fix: Inform user about MongoDB connection errors (invalid database/collection)

---

.github/PULL_REQUEST_TEMPLATE.md

Our PR template mentions that gems need to be built and tested against Enterprise Search, but does not explain how to do so. This PR adds a link to the document that has this instruction.

Update pull request template to include a link to instruction how to build and test gems

---

lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

This change attempts to use MongoDB client in such a way that the application does not leak threads any more. Somehow usage of `client.new` and `client.close` still left connections hanging after all the classes needed for sync are destroyed.
Switching to new syntax seems to properly recycle threads and stop the leaks:
```ruby
Mongo::Client.new(@host, args) do |client|
end
```
Fix thread leak when using MongoDB connector.

Optimize lifecycle of MongoDB client

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
docs/CONFIG.md
docs/CONNECTOR_PROTOCOL.md
docs/CONTRIBUTING.md
docs/DEVELOPING.md
docs/INTERNAL.md
docs/RELEASING.md
docs/SECURITY.md
docs/SUPPORT.md
docs/TERMINOLOGY.md

- [Connector service documentation (#367)](https://github.com/elastic/connectors-ruby/pull/367)

[8.5] Connector service documentation (#367)

---

lib/connectors/mongodb/connector.rb
lib/core/sync_job_runner.rb

Remove symbols and `with_indifferent_access` and stop using symbols to improve memory usage/recycling + performance of the connector. Usage of `with_indifferent_access` affects performance heavily + produces unnecessary memory overhead while only adding minor utility improvements.

use strings everywhere

---

lib/utility/es_client.rb

Optimisation change - as written in the comment in the PR, Elasticsearch client by default clones the arguments that are passed into it before processing the data.
This PR stops cloning the arguments to reduce the memory usage of bulk function. For example if the size of bulk request is 50MB, then call to `.bulk` will make it 100MB memory until bulk request finishes. Therefore, we don't use the original method, instead the original method is copied into `patched_bulk` method and `.clone` usage is deleted.
Decrease the amount of memory used by the connector service when sending bulk requests to Elasticsearch.

Add an elasticsearch client bulk patch to reduce memory usage

---

lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

This change updates the way the documents from MongoDB collections are gathered and sent to Elasticsearch.
Before the data is ingested like this:
```ruby
client[@collection].find.each do |document|
doc = document.with_indifferent_access
yield serialize(doc)
end
```
Problem with this code seems to be that all documents that were collected from MongoDB are kept in memory until the end of `.each` method call. To reduce the memory footprint we switch to explicit manual cursor paging:
```ruby
while true
found_count = 0
view = cursor.skip(skip).limit(PAGE_SIZE)
view.each do |document|
yield serialize(document)
found_count += 1
end
break if found_count == 0
skip += PAGE_SIZE
end
```
This way we keep in memory only one page of data and ready to GC the data with each `while` iteration.
Decrease …

Make better use of memory for Mongo connector when iterating over documents

---

lib/utility/es_client.rb

Reverts elastic/connectors-ruby#364
The change was tested in the batch with the other changes and seemed like something that reduces our memory usage significantly.
After thorough testing I wasn't able to find correlation between this change and actual memory usage reduction, thus reverting it.
A little meta about testing:
The assumption was that `.clone` function is a deep cloning function, but documentation states that it's a _shallow_ copy. `arguments` that are passed into the function for us consists only two properties: `body` and `pipeline` where `body` is an array and `pipeline` is a string.
Therefore shallow clone _should not copy the array_ which is the largest size object there. Testing showed that it's indeed the case and amount of memory is approximately the same.

Revert "Add an elasticsearch client bulk patch to reduce memory usage"

---

lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

- [Make better use of memory for Mongo connector when iterating over documents (#362)](https://github.com/elastic/connectors-ruby/pull/362)

[8.5] Make better use of memory for Mongo connector when iterating over documents (#362)

---

lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

- [Optimize lifecycle of MongoDB client (#363)](https://github.com/elastic/connectors-ruby/pull/363)

[8.5] Optimize lifecycle of MongoDB client (#363)

---

lib/utility/es_client.rb

- [Add an elasticsearch client bulk patch to reduce memory usage (#364)](https://github.com/elastic/connectors-ruby/pull/364)

[8.5] Add an elasticsearch client bulk patch to reduce memory usage (#364)

---

lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

- [Fix: Inform user about MongoDB connection errors (invalid database/collection) (#368)](https://github.com/elastic/connectors-ruby/pull/368)

[8.5] Fix: Inform user about MongoDB connection errors (invalid database/collection) (#368)

---

lib/app/preflight_check.rb
lib/core/native_scheduler.rb
lib/core/scheduler.rb
lib/core/single_scheduler.rb
lib/utility/errors.rb
spec/app/preflight_check_spec.rb
spec/core/native_scheduler_spec.rb
spec/core/single_scheduler_spec.rb

- [Add Authentication checks to preflight check and connector settings retrieval (#372)](https://github.com/elastic/connectors-ruby/pull/372)

[8.5] Add Authentication checks to preflight check and connector settings retrieval (#372)

---

lib/connectors/base/connector.rb
lib/connectors/example/connector.rb
lib/core/configuration.rb
spec/core/configuration_spec.rb

- [Allow strings and symbols for configurable fields in connectors (#380)](https://github.com/elastic/connectors-ruby/pull/380)

[8.5] Allow strings and symbols for configurable fields in connectors (#380)

---

lib/connectors/example/connector.rb
lib/core/sync_job_runner.rb
spec/core/sync_job_runner_spec.rb

- [Termination of connectors shows error (#381)](https://github.com/elastic/connectors-ruby/pull/381)

[8.5] Termination of connectors shows error (#381)

---

connectors_service.gemspec
connectors_utility.gemspec
lib/connectors/base/connector.rb
lib/connectors/example/connector.rb
lib/connectors/gitlab/connector.rb
lib/connectors/registry.rb
lib/core/sync_job_runner.rb

See https://elastic.slack.com/archives/C03GAPTQ2JF/p1667590997792289
* https://github.com/elastic/connectors-ruby/pull/385 introduced a new `job_description` argument for connectors, but we weren't consistent about its usage, and non-mongo connectors couldn't be created.

Ensure connector instantiations line up

---

lib/core/elastic_connector_actions.rb
lib/core/sync_job_runner.rb
spec/core/elastic_connector_actions_spec.rb
spec/core/sync_job_runner_spec.rb

looks up the filtering rules in `.elastic-connectors` and saves them into `.elastic-connectors-sync-jobs`.
With latest Kibana, choosing "build a connector", running the example connector, and triggering a sync, you get a `.elastic-connectors-sync-jobs` record like:
```
{
"_index": ".elastic-connectors-sync-jobs-v1",
"_id": "_mEnRIQB5rPmQXyEqZAB",
"_score": 1,
"_source": {
"connector_id": "9WEjRIQB5rPmQXyEWJB2",
"status": "completed",
"worker_hostname": "Seans-MacBook-Pro-2.local",
"created_at": "2022-11-04T19:39:20.699+00:00",
"filtering": [
{
"domain": "DEFAULT",
"rules": [
{
"created_at": "2022-11-04T19:34:37.926Z",
"field": "_",
"id": "DEFAULT",
"order": 0,
"policy": "include",
"rule": "regex",
"updated_at": "2022-11-04T19:34:37.926Z",
"value": ".*"
}
],
"advanced_snippet": { …
```

Persist filtering in job records

---

spec/core/sync_job_runner_spec.rb

This test raises an Exception, which is not rescued -> treated like something, which stopped the sync job thread (was not covered before with existing tests).

Add unit test, when a sync thread is stopped

---

lib/connectors/base/connector.rb
spec/connectors/base/connector_spec.rb
spec/connectors/mongodb/connector_spec.rb
spec/core/connector_settings_spec.rb

This PR changes the key used for extracting the advanced filter config to reflect the key used in the connectors mapping.
* https://github.com/elastic/connectors-ruby/pull/385

Use key specified in connectors mapping for advanced filter config

---

docs/CONNECTOR_PROTOCOL.md
lib/core/elastic_connector_actions.rb

This PR adds generic and connector-specific metadata to connector protocol and job index mapping

Add metadata to connector protocol and job index mapping

---

lib/connectors/base/connector.rb
lib/connectors/base/simple_rules_parser.rb
lib/connectors/mongodb/connector.rb
lib/connectors/mongodb/mongo_rules_parser.rb
lib/core/elastic_connector_actions.rb
lib/core/sync_job_runner.rb
spec/connectors/mongodb/connector_spec.rb
spec/connectors/mongodb/mongo_rules_parser_spec.rb
spec/core/elastic_connector_actions_spec.rb
spec/core/sync_job_runner_spec.rb

Created a base rules parser for filtering rules and a mongo-specific implementation.

[Mongo] add "simple" pre-processing filtering logic

---

spec/connectors/base/adapter_spec.rb
spec/connectors/base/connector_spec.rb
spec/connectors/base/custom_client_spec.rb
spec/connectors/example/connector_spec.rb
spec/connectors/gitlab/adapter_spec.rb
spec/connectors/gitlab/connector_spec.rb
spec/connectors/gitlab/extractor_spec.rb
spec/connectors/mongodb/connector_spec.rb
spec/connectors/mongodb/mongo_rules_parser_spec.rb
spec/connectors/registry_spec.rb
spec/core/configuration_spec.rb
spec/core/connector_settings_spec.rb
spec/core/elastic_connector_actions_spec.rb
spec/core/heartbeat_spec.rb
spec/core/ingestion/console_sink_spec.rb
spec/core/ingestion/es_sink_spec.rb
spec/core/sync_job_runner_spec.rb
spec/utility/bulk_queue_spec.rb
spec/utility/common_spec.rb
spec/utility/exception_tracking_spec.rb
spec/utility/logger_spec.rb

As discussed in https://github.com/elastic/connectors-ruby/pull/389, some of our tests are not following best practices.
Changes implemented here:
- Change `context` to `describe` if the context is mentioning a particular method
- Double check `#method` and `.method` - see if they actually call class or instance methods and fix it
- Group methods that are not under any `describe` to actually be under `describe '#method'` or `describe '.method'`

Make tests more consistent

---

lib/core/ingestion/ingester.rb
spec/core/ingestion/ingester_spec.rb

Adding simple logic to ignore documents that are bigger than allowed. If such document is encountered, it's ignored and a `warn` statement is produced.
Now connectors ignore the documents that are too large without attempting to ingest them.

Ignore large documents when ingesting the data

---

lib/core/elastic_connector_actions.rb
spec/core/elastic_connector_actions_spec.rb

Update the connector service to adopt the new index mapping of job index, where all connector data are group under key `connector`.

Update connector service to adopt the index mapping change

---

config/connectors.yml.example
docs/CONFIG.md
lib/app/config.rb
lib/app/dispatcher.rb
lib/core/ingestion/es_sink.rb
lib/core/jobs/consumer.rb
lib/core/sync_job_runner.rb
lib/utility/bulk_queue.rb
lib/utility/constants.rb
spec/app/dispatcher_spec.rb
spec/core/sync_job_runner_spec.rb

Now it's possible to specify maximum size/volume of ingestion queue.
```
max_ingestion_queue_size: X - data from the connector will be sent to Elasticsearch once X items were extracted
max_ingestion_queue_bytes: Y - data from the connector will be sent to Elasticsearch once bulk operation reaches Y bytes
```

Make it possible to specify maximum size/volume of ingestion queue

---

lib/connectors/base/advanced_snippet_against_schema_validator.rb
spec/connectors/base/advanced_snippet_against_schema_validator_spec.rb

This PR adds some more tests for fields constraints:
- Multiple fields constraints present
- Single constraint wrapped in an array
- Single constraint not wrapped in an array
Also unified the calls to `fields_constraint_violation` and `fields_constraints_violated?`.

Add more tests for fields constraints and unify two method calls

---

lib/connectors/base/advanced_snippet_against_schema_validator.rb
lib/connectors/mongodb/mongo_advanced_snippet_schema.rb
spec/connectors/base/advanced_snippet_against_schema_validator_spec.rb
spec/connectors/mongodb/mongo_advanced_snippet_against_schema_validator_spec.rb

This PR marks the "find.filter" field in the advanced snippet for MongoDB as optional so we don't return an invalid result, when it's missing.

Mark "find.filter" in the advanced snippet (MongoDB) as optional

---

lib/core/scheduler.rb
spec/core/scheduler_spec.rb

This is a bug reported in [slack](https://elastic.slack.com/archives/C03GAPTQ2JF/p1668460076978669). An initial sync will be triggered even operator never manually clicks `Sync` button or schedule a sync job.
This PR fixes the bug, so that the initial job will be triggered, only when operators explicitly enable and configure a schedule.

Start sync when scheduling is enabled and properly configured and there's no sync before

---

connectors_service.gemspec
connectors_utility.gemspec

Removes the usage of `lib/app/config` in gem spec, so we can bundle install the package directly using github

gemspecs: drop dependency on app/config

---

.backportrc.json

Forgot to do during bump from 8.6 to 8.5 😿

Fix backportrc for 8.6

---

lib/core/scheduler.rb
spec/core/scheduler_spec.rb

This will backport the following commits from `main` to `8.6`:
- [Start sync when scheduling is enabled and properly configured and there's no sync before (#432)](https://github.com/elastic/connectors-ruby/pull/432)

[8.6] Start sync when scheduling is enabled and properly configured and there's no sync before (#432)

---

docs/RELEASING.md

To help people not run into this:
```
bundle _2.3.15_ exec gem push .gems/*
Pushing gem to https://rubygems.org/...
You do not have permission to push to this gem. Ask an owner to add you with: gem owner connectors_service --add m.***@gmail.com
make: *** [push_gem] Error 1
```

Extending RELEASING.md to add instructions about logging into rubygems.

---

lib/connectors/mongodb/mongo_rules_parser.rb
spec/connectors/mongodb/mongo_rules_parser_spec.rb

This PR adds the missing implementation for MongoDB pre-processing simple rules for the rules 'starts_with', 'ends_with' and 'contains'. This fixes the bug that a user can select these rules in the UI, but a corresponding sync won't be started as the backend throws an error that the selected rule is unknown.

Fix: Implementation for MongoDB simple rules pre-processing for 'starts_with', 'ends_with' and 'contains' missing

---

lib/connectors_utility.rb

We need to use `Core::ConnectorJob` in ent-search so the file will be added to `utility.rb`

Include connector_job

---

lib/core/jobs/consumer.rb
lib/core/jobs/producer.rb
spec/app/dispatcher_spec.rb
spec/core/jobs/consumer_spec.rb
spec/core/jobs/producer_spec.rb

This PR is a follow-up for https://github.com/elastic/connectors-ruby/pull/427 and it addresses 2 things:
1. Add unit tests for `Jobs::Producer` and `Jobs::Consumer`
2. Replace Ruby native `loop` with `Concurrent::TimerTask` to have better thread control

Replace Consumer.loop by TimerTask

---

lib/core/connector_settings.rb
spec/core/connector_settings_spec.rb

This PR will update the connector status to either `connected` or `error` after a job completes.

Update connector status after job completes

---

connectors_service.gemspec

```
Fetching git@github.com:elastic/connectors-ruby
[!] There was an error while loading `connectors_service.gemspec`: Illformed requirement [#<Gem::Requirement:0x5da1a97f @requirements=[["~>", #<Gem::Version "1.0">], [">=", #<Gem::Version "1.0.1">]], @_sorted_requirements=[[">=", #<Gem::Version "1.0.1">], ["~>", #<Gem::Version "1.0">]], @_tilde_requirements=[["~>", #<Gem::Version "1.0">]]>]. Bundler cannot continue.
>        s.add_dependency dep.name, dep.requirement
ERROR: Bundle command failed!
```

Fix the extraction of the dependencies in the gemspec

---

connectors_utility.gemspec
docs/CONNECTOR_PROTOCOL.md
lib/app/dispatcher.rb
lib/connectors/base/connector.rb
lib/connectors/gitlab/connector.rb
lib/connectors/job_trigger_method.rb
lib/connectors/mongodb/connector.rb
lib/connectors_utility.rb
lib/core/connector_job.rb
lib/core/connector_settings.rb
lib/core/elastic_connector_actions.rb
lib/core/scheduler.rb
lib/core/sync_job_runner.rb
spec/connectors/base/connector_spec.rb
spec/connectors/mongodb/connector_spec.rb
spec/core/connector_settings_spec.rb
spec/core/scheduler_spec.rb
spec/core/sync_job_runner_spec.rb

This PR
1. adds `trigger_method` when creating a connector job
2. adds `configuration` when creating a connector job
3. Use `configuration`, `pipeline`, `index_name`, and `service_type` from job entity during job execution

Use connector data in job during execution

---

lib/utility/error_monitor.rb
spec/utility/error_monitor_spec.rb

Found a problem with error monitor class: instead of raising an error when number of errors in the window exceeds max_error_ratio, currently it just raises an error when number of errors that happened is equal to `window_size * max_error_ratio`.
Bug happened because the window of errors never considered successful documents as a part of equation - successful document was not reported into the window ever.

Fix a problem with error monitor and max_error_ratio being incorrectly handled

---

connectors_service.gemspec
lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

This PR introduces a quick fix to allow the usage of aggregation pipelines in 8.6. We didn't have the time to check, whether we run into the same memory leak problems as for find. We have to probably reiterate on that in 8.7. Also we should use a common abstraction for the document yielding (at least for MongoDB) to cleanup yield_documents.

Fix: MongoDB aggregation pipelines not working

---

lib/connectors/mongodb/mongo_advanced_snippet_snake_case_transformer.rb
spec/connectors/mongodb/mongo_advanced_snippet_snake_case_transformer_spec.rb

[8.6] Fix: Add nil guard for advanced snippet during transformation (#479)

---

lib/connectors/mongodb/mongo_rules_parser.rb
spec/connectors/mongodb/mongo_rules_parser_spec.rb

Backports the following commits to 8.6:
- Fix: Implementation for MongoDB simple rules pre-processing for 'starts_with', 'ends_with' and 'contains' missing (#458)

[8.6] Fix: Implementation for MongoDB simple rules pre-processing for 'starts_with', 'ends_with' and 'contains' missing (#458)

---

lib/core/filtering/simple_rules/validation/simple_rules_schema.rb
spec/core/filtering/simple_rule/single_rule_against_schema_validator_spec.rb
spec/support/shared_examples/filtering.rb

We should allow that the DEFAULT simple rule uses a match all regex.

Fix: Exclude DEFAULT simple rule from match all regex check

---

lib/connectors/base/connector.rb
spec/connectors/base/connector_spec.rb

This PR makes the advanced snippet accessible with symbols and keys so it doesn't fail for aggregation pipelines and find queries in MongoDB.

Fix: Advanced Snippet should be accessible with Strings and Symbols

---

lib/connectors/tolerable_error_helper.rb

Add the following exceptions to `fatal_exception_classes`
1. Core::ConnectorNotFoundError
2. Core::ConnectorJobNotFoundError
3. Core::ConnectorJobCanceledError
4. Core::ConnectorJobNotRunningError

Add more fatal exceptions

---

lib/connectors/mongodb/connector.rb
spec/connectors/mongodb/connector_spec.rb

We now check if a pipeline is nil and set it to an empty array, if that's the case, so the sync job won't crash.

Fix: [MongoDB Connector] Missing aggregation pipeline crashes sync job

---

lib/app/config.rb
lib/utility/es_client.rb
spec/app/config_spec.rb
spec/utility/es_client_spec.rb

From SDH https://github.com/elastic/sdh-enterprise-search/issues/1022
On cloud, we now need to pass-through the x-elastic-app-auth header.
This PR is a reflection of Python PR https://github.com/elastic/connectors-python/pull/243 and just makes it possible to specify `elasticsearch.headers` in config file. These settings are then passed to elasticsearch client when it's initialised.
[](https://github.com/elastic/connectors-python/pull/243)

Make it possible to send headers to Elasticsearch clients from config

---

connectors_utility.gemspec

Makes it easier to use the `connectors_utility` gem as a dependency if we don't pin the `activesupport` version.

Relax activesupport dependency requirement

---

docs/CONNECTOR_PROTOCOL.md

Update the connector protocol to support `custom_scheduling`.
These are being introduced here: https://github.com/elastic/ent-search/pull/7201
* https://github.com/elastic/ent-search/pull/7201

Add custom_scheduling to connector protocol

---

Gemfile.lock
Makefile

See the slack thread: https://elastic.slack.com/archives/CGRRUP4L9/p1673383147442159?thread_ts=1673380391.857499&cid=CGRRUP4L9
See the rbenv issue where this fix was found: https://github.com/rbenv/ruby-build/issues/1691#issuecomment-752802171

Fix makefile for arm64

---

Gemfile
Gemfile.lock

This PR will updata `elasticsearch` client to the latest public version 8.6.0

Update elasticsearcy client to 8.6.0

---

Gemfile.lock

Bump rack to 2.2.6.2
Resolves the following dependabot issues:
- https://github.com/elastic/connectors-ruby/security/dependabot/12
- https://github.com/elastic/connectors-ruby/security/dependabot/13
- https://github.com/elastic/connectors-ruby/security/dependabot/14

Bump rack to 2.2.6.2

---

lib/core/elastic_connector_actions.rb
spec/core/elastic_connector_actions_spec.rb

Add method to update `custom_scheduling.[key].last_synced` value with current time.

Add method for updating custom_scheduling last_synced

---

lib/app/dispatcher.rb
lib/core/connector_job.rb
lib/core/elastic_connector_actions.rb
lib/core/job_cleanup.rb
lib/core/jobs/consumer.rb
spec/core/job_cleanup_spec.rb

This PR ensures that the content indices of existing connectors are not deleted, when cleaning up orphaned jobs.

Don't delete content indices used by existing connectors

---

lib/core/elastic_connector_actions.rb
lib/core/sync_job_runner.rb
spec/core/sync_job_runner_spec.rb

This PR resets `last_sync_error`, and update `status` to `connected` when claiming a job

Reset last_sync_error when claiming a job

---

docs/CONNECTOR_PROTOCOL.md
lib/core/elastic_connector_actions.rb

Connected to issue https://github.com/elastic/enterprise-search-team/issues/3729
Updating connectors protocol to reflect the changes in the PR:
- adding "dynamic: false" to both indices

Add id to connector indices + dynamic: false

---

docs/CONNECTOR_PROTOCOL.md
lib/connectors/base/connector.rb
lib/core/configuration.rb
lib/core/connector_settings.rb
lib/utility/constants.rb
spec/core/configuration_spec.rb
spec/core/connector_settings_spec.rb

This PR implements new connector features structure:
```
{
"features": {
"sync_rules": {
"basic" : { "enabled" : true },
"advanced": {"enabled":true }
}
}
```
While this structure is also implemented and used, old structure is still maintained and used for backwards compatibility.

Implement nested features

---

lib/connectors/crawler/scheduler.rb
lib/core/scheduler.rb
spec/connectors/crawler/crawler_scheduler_spec.rb
spec/core/scheduler_spec.rb

The connector will start syncing immediately if its scheduling is enabled and it's never synced.
This PR fixes this bug, and makes the job scheduling respect the crontab:
It gets the next sync time from `now`, and compares it with `now` + `poll_interval`. It will trigger the sync if the next sync time happens before the next poll. This is consistent with the python implementation.
A follow-up PR is needed to update `ent-search` gem when this is merged.

Fix the bug that connector starts sync immediately when scheduled

---

lib/connectors/crawler/scheduler.rb
lib/core/scheduler.rb
spec/connectors/crawler/crawler_scheduler_spec.rb
spec/core/scheduler_spec.rb

This will backport the following commits from `main` to `8.7`:
- [Fix the bug that connector starts sync immediately when scheduled (#531)](https://github.com/elastic/connectors-ruby/pull/531)

[8.7] Fix the bug that connector starts sync immediately when scheduled (#531)

---

lib/core/connector_job.rb
lib/core/job_cleanup.rb
spec/core/job_cleanup_spec.rb

This will backport the following commits from `main` to `8.7`:
- [Rename stuck jobs to idle jobs (#535)](https://github.com/elastic/connectors-ruby/pull/535)

[8.7] Rename stuck jobs to idle jobs (#535)

---

.backportrc.json

With the current format we miss backports for PRs labeled with "8.7.0.0" as we hardcoded three numbers.

Allow arbitrary levels of postfix versions in .backportrc

---

lib/connectors_sdk/share_point/authorization.rb

This is based off of https://github.com/elastic/ent-search/pull/7352/files, but for connector packages
* normal connectors: https://github.com/elastic/ent-search/pull/7352/files
* docs: https://github.com/elastic/enterprise-search-pubs/pull/3201
Fixes a bug where Sharepoint Online Connector Packages couldn't be connected by non-global-admins, even if admin consent was granted.
- not doing this, since we aren't actually fixing old version of enterprise search, but the connector package just happens to live in this old branch

remove prompt=consent in favor of prompt=select_account

---

.backportrc.json

Small thing - there are no more 8.6.* releases left, so no point to have it in backportrc.

Remove 8.6 from backportrc

---

Gemfile
Gemfile.lock

Resolves dependabot alerts: https://github.com/elastic/connectors-ruby/security/dependabot

Bump rack and activesupport

---

.buildkite/pipeline.yml
.buildkite/scripts/run_ci_step.sh
.buildkite/scripts/run_command.sh

Migrates the primary pipeline from Jenkins to Buildkite

Add Primary Buildkite Pipeline Migration

---

catalog-info.yaml

Adds the missing team name in the `catalog-info.yaml` file for Buildkite / Backstage.

[CI] [Buildkite] Add Proper Team in Catalog Info File

---

Dockerfile
Gemfile.lock
Makefile

Bump Dockerfile to use `ubuntu:mantic-20231011` for its base image to reduce the number of vulnerable libraries/packages installed with the image.
Note: This relates to an internal developer productivity issue; I will link this issue from there.

Update to latest ubuntu image in dockerfile to avoid lots of vulnerabilities

---

.buildkite/pipeline.yml
.buildkite/scripts/run_ci_step.sh
.buildkite/scripts/run_command.sh

This will backport the following commits from `main` to `8.3`:
- [Add Primary Buildkite Pipeline Migration (#571)](https://github.com/elastic/connectors-ruby/pull/571)

[8.3] Add Primary Buildkite Pipeline Migration (#571)

---

Dockerfile

The original base image was EOLed on Jul 2024, causing the Docker build in CI failed (because EOLed repositories are moved to `old-releases.ubuntu.com`)
https://github.com/elastic/connectors-ruby/blob/255cf4ce4133e30ead41a58c2be9bed734451850/Dockerfile#L1
This PR updates the base image to the latest `noble-20241118.1`.

Update the ubuntu base image to noble-20241118.1

---

Gemfile
Gemfile.lock
connectors_utility.gemspec

This PR upgrades dependency `fugit` and `mime-types`

Upgrade fugit and mime-types
