elastic/connectors-ruby

- connectors-api/src/main/ruby/connectors_errors.rb
- connectors-api/src/main/ruby/connectors_monitor.rb
- connectors-api/src/test/ruby/connectors_monitor_test.rb
- connectors-stubs/src/main/ruby/app_config.rb
- connectors-stubs/src/main/ruby/swiftype_exception_tracking.rb
Moves `Connectors::ConnectorsAPI::Monitor` to this repo
> move connectors monitor

- README.md
> adding tech preview verbiage

- lib/connectors_sdk/office365/extractor.rb
- spec/connectors_sdk/base/custom_client_spec.rb
- spec/connectors_sdk/base/extractor_spec.rb
- spec/connectors_sdk/sharepoint/extractor_spec.rb
- spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb
> Improve test coverage

- Gemfile.lock
- lib/app/app.rb
- lib/connectors_sdk/share_point/http_call_wrapper.rb
- spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb
Related discussion: https://elastic.slack.com/archives/C030MMRDFL3/p1649142679941249
* https://github.com/elastic/ent-search/pull/6421
> Index permissions in document

- Gemfile.lock
- lib/app/app.rb
- lib/connectors_sdk/share_point/http_call_wrapper.rb
- spec/connectors_sdk/sharepoint/http_call_wrapper_spec.rb
Backports the following commits to 8.2:
- Index permissions in document (#68)
> [8.2] Index permissions in document (#68)

- .ci/pipelines/connectors.groovy
- Gemfile
- Gemfile.lock
- README.md
- make.bat
- win32/getmsys2.vbs
- win32/install.bat
backports https://github.com/elastic/connectors/pull/61/files to 8.2
> [8.2] backport windows build

- docs/RELEASING.md
Updates I've come up with while going through this process for the 8.2.0 Elastic release.
> Updates to the release steps

- README.md
- docs/DEVELOPING.md
Prompted by community feedback: https://elasticstack.slack.com/archives/C018C7B9T5F/p1650358554437959?thread_ts=1650028814.362279&cid=C018C7B9T5F
> Clarify rbenv requirement

- lib/app/app.rb
Just removing some logging that isn't appropriate.
> Remove some logging from the Sinatra app

- .ci/pipelines/connectors.groovy
Fixing our slack notifications
> Fix the slack notification for main failures

- lib/app/connector.rb
Small fix for https://github.com/elastic/connectors/pull/130 - getting utc time instead of local
> small fix to get utc time

- .gitignore
Working with vim on the repo I have *.swp files that I don't wanna commit.
> Add *.swp to gitignore

- lib/app/connector.rb
- lib/app/console_app.rb
- lib/core/elastic_connector_actions.rb
- lib/core/sync_job_runner.rb
Getting scheduling setup (on/off, running the sync now or on schedule) possible from cli.
> Getting scheduling setup possible from cli

- connectors_utility.gemspec
- lib/utility/elasticsearch/index/text_analysis_settings.rb
- spec/utility/elasticsearch/text_analysis_settings_spec.rb
This will fix a small typo and some specs to avoid this issue in the future.
> Fix incorrect access to instance variable

- README.md
This PR fixes a small misspelling in the readme
> contirubions → contributions

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- connectors_utility.gemspec
- docs/CONTRIBUTING.md
- docs/RELEASING.md
- docs/SUPPORT.md
> renamed repo

- lib/utility/elasticsearch/index/text_analysis_settings.rb
We want to make UnsupportedLanguageCode more readable for customers so this PR will add a message to the exception class.
> Add error message to UnsupportedLanguageCode

- README.md
- docs/CONNECTOR_PROTOCOL.md
Adds the connector protocol document.
> Add connector protocol document

- Gemfile
- Gemfile.lock
> updated tzinfo

- lib/app/worker.rb
Make the heartbeat run immediately.
> Start heartbeat immediately

- .ci/jobs/nightly-qa.yml
- .ci/pipelines/nightly-qa.groovy
Runs a nightly QA job for an e2e test
> nightly jenkins job 

- Makefile
- lib/utility/elasticsearch/index/mappings.rb
- spec/utility/elasticsearch/mappings_spec.rb
Backport of https://github.com/elastic/connectors-ruby/pull/231
> [8.4] backport mappings changes

- lib/connectors/example/connector.rb
- lib/connectors/registry.rb
- spec/utility/es_client_spec.rb
> Rename stub connector to example connector

- docs/CONNECTOR_PROTOCOL.md
This fixes the connector protocol sequence diagram in the connector protocol.
> Fix connector protocol sequence diagram

- Dockerfile
- Makefile
- README.md
- lib/app/config.rb
- lib/utility/es_client.rb
- script/run_in_docker.sh
We no longer have a HTTP server. Fixed the Docker environement
> Fixed the Docker environement

- README.md
- config/connectors.yml.example
- docs/SUPPORT.md
Backports the following commits to 8.4:
- Connector Service Documentation (#185)
> [8.4] Connector Service Documentation (#185)

- docs/CONNECTOR_PROTOCOL.md
- lib/core/elastic_connector_actions.rb
- spec/core/elastic_connector_actions_spec.rb
This is a follow-up PR on https://github.com/elastic/connectors-ruby/pull/282, extracted from https://github.com/elastic/connectors-ruby/pull/284
> Follow-up on PR-282

- lib/core/connector_settings.rb
- spec/core/connector_settings_spec.rb
see: https://github.com/elastic/connectors-ruby/pull/283#issuecomment-1239604384
> Fix brittle pipeline param access

- config/connectors.yml.example
- lib/app/config.rb
- lib/app/dispatcher.rb
- lib/app/dispatcher_app.rb
- lib/core/scheduler.rb
- lib/utility/constants.rb
- spec/app/dispatcher_spec.rb
> Make connector service gracefully handle errors

- connectors_utility.gemspec
- lib/app/dispatcher.rb
- lib/connectors/crawler/scheduler.rb
- lib/core/scheduler.rb
- spec/app/dispatcher_spec.rb
- spec/core/scheduler_spec.rb
> Move service type check to xxx_registered? methods

- lib/connectors/connector_status.rb
- lib/connectors/sync_status.rb
Apply the BE status change proposed [here](https://github.com/elastic/enterprise-search-team/issues/3153#issuecomment-1291782149)
> Update job status

- lib/connectors/base/connector.rb
- lib/core/connector_settings.rb
- lib/core/elastic_connector_actions.rb
- lib/core/output_sink/es_sink.rb
- lib/core/sync_job_runner.rb
- spec/core/elastic_connector_actions_spec.rb
- spec/core/sync_job_runner_spec.rb
- spec/support/shared_examples.rb
> Report metadata during job execution

- spec/connectors/base/connector_spec.rb
- spec/connectors/gitlab/connector_spec.rb
- spec/core/elastic_connector_actions_spec.rb
- spec/core/filtering/validation_job_runner_spec.rb
Saw @artem-shelkovnikov's PR about refactoring some tests (#415) to adhere more to best practices. Looked through my recent work and did the same thing.
> Refactor some test methods to adhere to spec best practices

- lib/connectors/mongodb/connector.rb
- lib/utility/filtering.rb
Replace the check, if filtering is an array with the available utility function.
> Use utility function for filter extraction.

- lib/app/app.rb
- lib/core.rb
- lib/core/connector_job.rb
- lib/core/connector_settings.rb
- lib/core/elastic_connector_actions.rb
- spec/core/connector_job_spec.rb
> Add Job Entity

- spec/connectors/registry_spec.rb
Add some missing tests to `registry_spec.rb` to have more coverage.
> Add tests to registry_spec

- lib/connectors/base/connector.rb
- lib/connectors/mongodb/connector.rb
- lib/connectors/mongodb/mongo_advanced_snippet_snake_case_transformer.rb
- lib/connectors/mongodb/mongo_filter_snake_case_transformer.rb
- lib/core/filtering/transform/filter_transformer.rb
- lib/core/filtering/transform/filter_transformer_facade.rb
- lib/core/filtering/transform/transformation_target.rb
- spec/connectors/mongodb/connector_spec.rb
- spec/connectors/mongodb/mongo_filter_snake_case_transformer_spec.rb
- spec/core/filtering/transform/filter_transformer_facade_spec.rb
- spec/core/filtering/transform/filter_transformer_spec.rb
This PR introduces filtering transformation capabilities to the framework. It also implements snake casing for MongoDB.
> Fix: snake_case MongoDB filtering

- .github/PULL_REQUEST_TEMPLATE.md
See: https://elastic.slack.com/archives/C01795T48LQ/p1673535527143469?thread_ts=1673525897.348189&cid=C01795T48LQ
> Add more pull request checklist items

- Gemfile.lock
> Bump tzinfo-data

- Gemfile
- Gemfile.lock
> Bump ES gem to 8.7.0

- lib/app/console_app.rb
- lib/core/connector_settings.rb
- lib/core/scheduler.rb
- spec/connectors/crawler/crawler_scheduler_spec.rb
- spec/core/scheduler_spec.rb
This PR modifies the structure of `scheduling`, to accommodate different types of scheduling.
> Modify the structure of scheduling

- Gemfile
- Gemfile.lock
Bumping elasticsearch gem to 8.8.0
> Bump elasticsearch gem to 8.8.0
